name: Deploy Docling Serve Configuration

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**
    paths:
      - 'docling-serve-prod-config/**'
      - '.github/workflows/deploy-docling-serve.yml'

jobs:
  deploy-config:
    name: Deploy Docling Serve Config
    # This job only runs if the commit message includes the trigger phrase `[deploy docling]`
    if: "github.ref_name == 'main' || contains(github.event.head_commit.message, '[deploy docling]')"
    if: "!contains(github.event.head_commit.message, '[bot]')"
    runs-on: ubuntu-latest

    env:
      # GCP Configuration (same as your SmolDocling setup)
      GCP_PROJECT_ID: "experio-staging"
      GCP_REGION: "us-central1"
      GCE_ZONE: "us-central1-a"
      GCE_INSTANCE: "docling-stating-gpu-2"
      
      # Deployment Configuration
      CONFIG_DIR: "docling-serve-prod-config"
      REMOTE_DIR: "~/docling-serve-prod-config"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Copy configuration files to GCE instance
        run: |
          echo "📁 Copying docling-serve-prod-config to ${{ env.GCE_INSTANCE }}..."
          
          # Remove existing directory to ensure clean overwrite
          gcloud compute ssh ${{ env.GCE_INSTANCE }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --zone=${{ env.GCE_ZONE }} \
            --command="sudo rm -rf ${{ env.REMOTE_DIR }}" || true
          
          # Copy the entire config directory to the instance  
          gcloud compute scp \
            --project=${{ env.GCP_PROJECT_ID }} \
            --zone=${{ env.GCE_ZONE }} \
            --recurse \
            ${{ env.CONFIG_DIR }} \
            ${{ env.GCE_INSTANCE }}:${{ env.REMOTE_DIR }}
          
          # Setup configuration and permissions
          gcloud compute ssh ${{ env.GCE_INSTANCE }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --zone=${{ env.GCE_ZONE }} \
            --command="
              cd ${{ env.REMOTE_DIR }} &&
              echo '📋 Setting up configuration...' &&
              cp .example.env .env &&
              echo '✅ Copied .example.env to .env' &&
              chmod +x start.sh &&
              echo '✅ Made start.sh executable' &&
              ls -la
            "

      - name: Deploy and restart Docling Serve
        run: |
          echo "🚀 Deploying Docling Serve with load balancing..."
          
          gcloud compute ssh ${{ env.GCE_INSTANCE }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --zone=${{ env.GCE_ZONE }} \
            --command="
              cd ${{ env.REMOTE_DIR }} && 
              sudo ./start.sh
            "